# NumPy Lesson
This lesson will go over the difference between python lists and NumPy arrays.


In [1]:
import os
import numpy
def calculate_distance(coords1,coords2):
    xdist = coords1[0]-coords2[0]
    ydist = coords1[1]-coords2[1]
    zdist = coords1[2]- coords2[2]
    distance = numpy.sqrt(xdist**2+ydist**2+zdist**2)
    return distance
def bond_check(distance, dmin=0, dmax=1.5):
    """
    This function checks a distance and determines if it is a bond.
    Inputs:distance, minimum cutoff value for the bond, maximum cutoff values forthe bond. 
    Default for minimum is 0. Default for the Maximum is 1.5
    Returns True of False for the bond.
    """
    if distance>dmin and distance<dmax:
        return True
    else:
        return False
def open_xyz(filename):
    """
    This fuction process an xyz file.
    Input: filename or filepath
    Output: list of symbols and array of coordinates
    """
    xyz_file = numpy.genfromtxt(fname=filename, dtype='unicode',skip_header=2)
    symbols = xyz_file[:,0]
    coordinates = xyz_file[:,1:]
    coordinates = coordinates.astype(float)
    return(symbols,coordinates)
    
file_location = input('Enter file path for the xyz file to analyze:')
symbols,coordinates = open_xyz(file_location)
num_atoms=len(symbols)
for num1 in range(0,num_atoms):
    for num2 in range (0,num_atoms):
        if num1<num2:
            distance=calculate_distance(coordinates[num1],coordinates[num2])
            if bond_check(distance)is True:
                print(F'{symbols[num1]} to {symbols[num2]} : {distance:.3f}')
#array[row,column]

Enter file path for the xyz file to analyze:data/water.xyz
O to H1 : 0.969
O to H2 : 0.969


In [2]:
print(coordinates)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [16]:
oxygen_coordinate = coordinates[0]

In [23]:
translation_vector = [0.1, -0.1, 0]

In [24]:
print(oxygen_coordinate)

[ 0.       -0.007156  0.965491]


In [25]:
new_coord = []
for i in range(3):
    update = oxygen_coordinate[i] +translation_vector[i]
    new_coord.append(update)

In [26]:
print (new_coord)

[0.1, -0.107156, 0.965491]


In [27]:
type(oxygen_coordinate)

numpy.ndarray

In [31]:
#NumPy arrays let us add vectors without for loops
new_coord2 = oxygen_coordinate + translation_vector
print (new_coord2)

[ 0.1      -0.107156  0.965491]


In [32]:
type(new_coord)

list

In [33]:
new_coord + translation_vector

[0.1, -0.107156, 0.965491, 0.1, -0.1, 0]

# Creating NumPy Arrays

In [36]:
a1=numpy.array([2,1,0])
a2=numpy.array([1,3,5])
#What wiil this be?
print (a1+a2)
print (a1*a2)
#adds each element together??

[3 4 5]
[2 3 0]


In [37]:
# if we tried this with lists, our answers would be different
a1=[2,1,0]
a2=[1,3,5]
#does not Happen

In [38]:
new_water = coordinates + translation_vector

In [39]:
print(new_water)

[[ 0.1      -0.107156  0.965491]
 [ 0.1      -0.098514 -0.003471]
 [ 0.1       0.831026  1.207929]]


In [40]:
coordinates.shape

(3, 3)

In [42]:
#Find coordinates greater than 0 with NumPy
coordinates>0

array([[False, False,  True],
       [False,  True, False],
       [False,  True,  True]])

In [43]:
coordinates[coordinates>0]

array([0.965491, 0.001486, 0.931026, 1.207929])

# Array Axes

In [44]:
print(coordinates)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [48]:
coordinates.mean(axis=0)
# 0 = each column
# 1 = each row

array([0.        , 0.308452  , 0.72331633])